basePath: /api/v1
host: localhost:3000
info:
  contact:
    email: gustavodiasa2121@gmail.com
    name: Gustavo Dias
    url: https://github.com/charmingruby
  description: This is the kickstart for new Go APIs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Kickstart
  version: "1.0"
paths: {}
swagger: "2.0"
